Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/BeltExamWish/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.LoginReg.urls', namespace='loginReg')),
    url(r'^wishlist/', include('apps.WishList.urls', namespace='wishList')),
]

Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/apps/LoginReg/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^r_process$', views.r_process, name = 'products'),
    url(r'^l_process$', views.l_process, name = 'products'),
    # url(r'^success$', views.success, name = 'success'),
    url(r'^logout$', views.logout, name = 'logout'),
]

Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/apps/WishList/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^index$', views.index, name = 'index'),
    url(r'^addProductPage$', views.addProductPage, name = 'addProductPage'),
    url(r'^addProduct$', views.addProduct, name = 'addProduct'),
    url(r'^joinWish/(?P<id>\d+)$', views.joinWish, name = 'joinWish'),
    url(r'^showProduct/(?P<id>\d+)$', views.showProduct, name = 'showProduct'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name = 'delete'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name = 'remove'),
]

Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/apps/WishList/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.contrib import messages
import datetime
from ..LoginReg.models import User

class ProductManager(models.Manager):
    def addNewProduct(self, data, user_id):
        flag = True
        errs = []

        if len(data['product']) < 2:
            flag = False
            errs.append("product By field needs to have more than 2 characters.")

        if data['product'] == "":
            flag = False
            errs.append("product By field cannot be blank.")

        if flag:
            productCreate = self.create(
                product = data['product'],
                planned_user_id = user_id,
            )
            return (True, productCreate)
        else:
            return (False, errs)

class Product(models.Model):
    product = models.CharField(max_length=255)
    planned_user = models.ForeignKey(User, related_name='plannertrip')
    joining_user = models.ManyToManyField(User, related_name='joiningtrip')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProductManager()

Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/apps/WishList/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from ..LoginReg.models import User
from .models import Product
from django.core.urlresolvers import reverse
from django.db.models import Q
import datetime
from time import gmtime, strftime

def index(request):
    context = {  # Q and | allow me to do compare two columns
	'my_wish': Product.objects.filter(Q(planned_user_id=request.session['user_id']) | Q(joining_user =request.session['user_id'])),
	# for the user who's logged in:  -- I planned the trip ((or)) I joined the trip --
	'not_mine': Product.objects.all().exclude(Q(planned_user_id=request.session['user_id']) | Q(joining_user =request.session['user_id'])),
	# for the user who's logged in:  -- I DIDN'T plan the trip ((or)) I DIDN'T join the trip --
	'users': User.objects.get(id=request.session['user_id'])
	}
    return render(request,"WishList/index.html", context)

def addProductPage(request):
    return render(request,"WishList/addProductPage.html")

def addProduct(request):
    result = Product.objects.addNewProduct(request.POST, request.session['user_id'])
    if result[0]:
        print"*"*50
        print result
        return redirect(reverse("wishList:index"))
    else:
        for errs in result[1]:
			# messages.error(request, errs)
            return redirect(reverse("wishList:addProductPage"))
    return redirect(reverse("wishList:index"))

def joinWish(request,id):
	joining = User.objects.get(id=request.session['user_id'])
	product_joining = Product.objects.get(id=id)
	product_joining.joining_user.add(joining)
	return redirect(reverse('wishList:index'))

def showProduct(request,id):
	context = {
		'products': Product.objects.get(id = id),
	}

	return render(request,"WishList/product_page.html", context)

def delete(request, id): #item_id
    Product.objects.get(id=item_id).delete()
    return redirect(reverse('wishList:index'))

def remove(request, id): #item_id
    user = User.objects.get(id=request.session['user_id'])
    item = Product.objects.get(id=id)
    item.joining_user.remove(user)
    return redirect(reverse('wishList:index'))

Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/apps/WishList/templates/WishList/addProductPage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Product Page</title>
  </head>
  <body>
    <a href="{% url "wishList:index" %}">Back</a>
    <h3>Create a New Wish List Item</h3>
     <form class="" action="{% url "wishList:addProduct" %}" method="post">
        {% csrf_token %}
        <p>Item/Product: <input type="text" name="product"></p>
        <p><input type="submit"value="Add"></p>
     </form>

  </body>
</html>

Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/apps/WishList/templates/WishList/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>WishList</title>
  </head>
  <body>
    <a href="{% url 'loginReg:logout' %}">Logout</a><br><br>
    <a href="{% url 'wishList:addProductPage' %}">Add Product</a>
    <h2>Hello {{users.name}}</h2>
    <h3>Your Wish List:</h3>

    <fieldset>
      <legend></legend>
        <table>
          <tr>
            <th>Item</th>
            <th>Added by</th>
            <th>Date Added</th>
            <th>Action</th>
          </tr>
            {% for item in my_wish %}
    			<tr>
    				<td> <a href="{% url 'wishList:showProduct' id=item.id %}"> {{item.product}} </a> </td>
    				<td>{{item.planned_user.name}}</td>
    				<td>{{item.created_at}}</td>
            {% if users == item.user %}
            <td><a href="{% url 'wishList:delete' item.id %}">Delete</a></td>
            {% else %}
            <td><a href="{% url 'wishList:remove' item.id %}">Remove from my Wishlist</a></td>
          </tr>
            {% endif %}
            {% endfor %}
    			</tr>


        </table>
    </fieldset>
    <br><br><br>
    <h2>this is all the other people wishlist</h2>
    <fieldset>
      <table>
        <tr>
          <th>Item</th>
          <th>Added by</th>
          <th>Date Added</th>
          <th>Action</th>
        </tr>
        {% for item in not_mine %}
				<tr>
					<td><a href="{% url 'wishList:showProduct' id=item.id  %}">{{item.product}}</a></td>
					<td>{{item.planned_user.name}}</td>
					<td>{{item.created_at}}</td>
          <td> <a href="{% url 'wishList:joinWish' id=item.id %}">Add to my WishList</a> </td>
				</tr>
			{% endfor %}
      </table>
    </fieldset>
  </body>
</html>

Python2/CodingDojo_Python2/Django/BELT_EXAM_WISH_COPY/BeltExamWish/apps/WishList/templates/WishList/product_page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{% url 'wishList:index' %}">Home</a><br><br>
    <a href="{% url 'loginReg:logout' %}">Logout</a><br>
    <h1>{{products.product}}</h1>
    <h3>Users who added this product/item under their wish list: </h3>
    {# {% for item in joiningusers %}
      <p>{{item.name}}</p>
    {% endfor %} #}
  </body>
</html>